# Generated by Django 4.1.3 on 2022-11-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0002_wine_grape'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='wine_image',
            field=models.ImageField(default='\\vine_app\\img\\default.jpg', upload_to='\\vine_app\\img'),
        ),
    ]
