# Generated by Django 4.1.3 on 2022-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0007_alter_wine_fragrance_alter_wine_taste'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.CharField(default='', max_length=100),
        ),
    ]
