# Generated by Django 4.1.3 on 2022-11-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0009_shelf_alter_wine_wine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='shelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vine_app.shelf'),
        ),
    ]
