# Generated by Django 4.1.3 on 2022-11-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0010_wine_shelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='shelf',
            new_name='shelf_id',
        ),
    ]
