# Generated by Django 4.1.3 on 2023-01-26 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0011_rename_shelf_wine_shelf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wine',
            name='crop_year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
