# Generated by Django 4.1.3 on 2023-02-02 11:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0012_shelf_title_alter_wine_crop_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='crop_year',
            field=models.PositiveIntegerField(default=1900, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='wine',
            name='fragrance',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='fun_facts',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='wine',
            name='shelf_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vine_app.shelf'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='taste',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='wine_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
