# Generated by Django 4.1.3 on 2023-02-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0013_alter_wine_crop_year_alter_wine_fragrance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
