# Generated by Django 4.1.3 on 2023-02-10 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0015_remove_shelf_shelf_id_alter_shelf_description_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='wine',
            name='crop_year',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AddField(
            model_name='shelf',
            name='cabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vine_app.cabinet'),
        ),
    ]
