# Generated by Django 4.1.3 on 2023-02-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0016_cabinet_alter_wine_crop_year_shelf_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='cabinet',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vine_app.cabinet'),
        ),
    ]
