# Generated by Django 4.1.3 on 2023-02-20 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vine_app', '0020_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='shelf_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='vine_app.shelf'),
        ),
    ]
